version: "3.3"

services:
    mysql:
        image: mysql:5.6
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./var/mysql/data:/var/lib/mysql
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: library
            MYSQL_ROOT_PASSWORD: password

    app:
        build: .
        container_name: app
        restart: always
        ports:
            - "8080:8080"
        environment:
            DB: user:password@(mysql:3306)/library
        depends_on: [mysql]
